### ISSUE TITLE
将最新版本向后移植到1.19.2（forge

### ISSUE THREAD

**Issue by QianFuv** [Jissee/Chess#1]
1.2版本不够玩（而且模型也不是很好-重点批评黑白棋是按钮

**Comment by Jissee** [comment]
你的建议已经收到，等我有空了来移植

**Comment by QianFuv** [comment]
> 你的建议已经收到，等我有空了来移植

感谢！！！期待新版本的发布！

**Comment by QianFuv** [comment]
别沉啊qwqqwqqwq

**Comment by Jissee** [comment]
抱歉，最近实在是太忙了😫☕，等 Minecraft 更新到 1.20.2 后跟进版本时我顺便向后移植到 1.18.2

**Comment by QianFuv** [comment]
好好好~ 谢谢XD

**Comment by QianFuv** [comment]
1.20.6出了 现在能否将高版本特性移植回1.19.2呢🤔

**Comment by Jissee** [comment]
死线是超大功率的[曲率引擎](https://santi.huijiwiki.com/wiki/%E6%9B%B2%E7%8E%87%E5%BC%95%E6%93%8E)加速时产生的航迹，航迹内光速为零。

死线并不稳定，被扰动之后可以扩展形成[慢雾](https://santi.huijiwiki.com/wiki/%E6%85%A2%E9%9B%BE)，此种慢雾中光速大于零，但仍然极低，甚至可以低至恒星系统逃逸速度，能够将恒星系变为[低光速黑洞](https://santi.huijiwiki.com/wiki/%E4%BD%8E%E5%85%89%E9%80%9F%E9%BB%91%E6%B4%9E)。

最近开发者正深陷“期末复习”这一慢雾中，并且正在各种作业的死线之间挣扎，同时还要启动并超频低光速下的（碳基）神经元控制系统，预计最快将在6月中旬脱离低光速区域。

**Comment by Jissee** [comment]
目前更新已经完成，但是网页审核需要一定时间，我可以先把文件给你。你需要什么版本的？
![image](https://github.com/Jissee/Chess/assets/50765103/4682049c-3cf7-492f-baed-5d77c05cbbf6)

**Comment by QianFuv** [comment]
啊 我需要1.19.2forge的 qwq

**Comment by Jissee** [comment]
1.19.2 恰好已经停止支持了，我重新帮你做吧，还要再花一点时间。ToT

**Comment by QianFuv** [comment]
啊这... 感觉1.19.4玩的人比1.19.2少很多 qwq

**Comment by Jissee** [comment]
仅此一份哦
[chess-1.19.2-3.0.zip](https://github.com/user-attachments/files/15776035/chess-1.19.2-3.0.zip)

**Comment by QianFuv** [comment]
好耶！

**Comment by Jissee** [comment]
可惜我来不及测试了，有什么问题再反馈吧

**Comment by QianFuv** [comment]
好的 我一会或者明天测试后反馈给您
