### ISSUE TITLE
Bug 和一些小建议

### ISSUE THREAD

**Issue by QianFuv** [Jissee/Chess#2]
https://www.youtube.com/watch?v=0YqIrtXVVsE
将骰子扔出后有时能捡起，但是地上会生成一个新骰子，然后就一生二......

ps. 骰子能不能也做成稿子一击就收到物品栏里面呀
ps1. 象棋棋子右键翻面是有啥作用嘛...好像没接触过象棋棋子翻面的玩法？
ps2. 军棋目前只能立放和平放，能加一个shift+右键翻面的设定嘛...这也是一种军棋的玩法

以上为1.19.2forge版本的反馈，希望可以采纳！

**Comment by Jissee** [comment]
0. 马上改；
1. 象棋也有翻翻棋的，但是手动布置棋子比较麻烦；
2. 同上，手动布置棋子有很大局限，而且这样会很复杂，因为多一个状态就要多写一种模型，反而很容易出错，我也实在不想做了。

**Comment by QianFuv** [comment]
后面就是几个建议啦 做不做取决于你
Bug 修好就 Ok

**Comment by Jissee** [comment]
[chess-1.19.2-3.1.zip](https://github.com/user-attachments/files/15779246/chess-1.19.2-3.1.zip)
再测一下

**Comment by Jissee** [comment]
[chess-1.19.2-3.1.zip](https://github.com/user-attachments/files/15779280/chess-1.19.2-3.1.zip)
刚才那个有bug，用这个

**Comment by QianFuv** [comment]
好滴 这就去测试

**Comment by QianFuv** [comment]
OK 又找到一个 Bug
连续扔两个骰子，如果这两个骰子在地上被合并为一组物品，就只会生成一个骰子方块，从而吞掉另一个（直接扔一组也会只生成一个骰子方块）
修改建议：如果是单个扔，无论是否在地上被合为一组都可以生成对应数量的骰子方块，如果一次性扔超过一个的骰子，则不生成方块

**Comment by Jissee** [comment]
我认为这个没必要改了，因为一盘棋用一个骰子就够了，合成多个骰子反而已经是浪费了，或者使用时注意一点，分开扔就行。而且骰子也很好合成，我设计的是一个骨块+一个红色染料+一个黑色染料。如果关于这个问题的反馈比较多，大家都认为有必要我再改。或者我直接去掉Q键投掷的功能。
